INHERIT: ../base.yml
site_name: Lenguajes de Marcas - Proyectos
site_dir: ../../docs/proyectos
  

# Page tree
nav:
  - Inicio: index.md
  - Proyecto 1: proyecto1.md
  - Proyecto 2: proyecto2.md
  - Proyecto 3: proyecto3.md


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iesalberticadiz
      name: IES Rafael Alberti en Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/IES-Rafael-Alberti/digitalizacion-gs
      name: Repositorio del módulo
