INHERIT: ../base.yml
site_name: Lenguajes de Marcas - Apuntes y referencias
site_dir: ../../docs/referencias

plugins:
  - search:
      lang: es

# Page tree
nav:
  - Inicio: index.md
  - UT1: ud1.md
  - UT2: ud2.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/IESAlbertiCadiz
      name: IES Alberti en Twitter
