site_name: Docs
theme:
  name: material
  language: es
  logo: assets/sello-rafael-alberti-imago-blanco.svg
  favicon: assets/sello-rafael-alberti-imago-blanco.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: daw-style
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - header.autohide
extra_css:
  - stylesheet/extra.css
plugins:
# Configuración de ejemplo, no se aplicará mientras que no se elimine este plugin de los .yml de cada proyecto
  - search:
      lang: es
  - with-pdf:
      author: Equipo educativo de 1º DAW del IES Rafael Alberti
      copyright: CC BY-SA 4.0
      #
      cover: true
      #back_cover: true
      cover_title: TITLE TEXT
      cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Tabla de contenidos
      #heading_shift: false

copyright: Contenido generado por el equipo educativo de 1º DAW del IES Rafael Alberti
